services:
  - type: static_site
    name: tecaigo-pitch-2026
    branch: main
    buildCommand: npm ci && npx next build --webpack
    staticPublishPath: ./out
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    autoDeployTrigger: commit
